#!/usr/bin/env node

const fs = require("fs");
const { Stellar } = require("./lib/sdk");

fs.writeFileSync(
  "pairs.json",
  JSON.stringify(
    ["escrowPair", "pairA", "pairB"].map(() => {
      const pair = Stellar.Keypair.random();
      return {
        secretSeed: pair.secret(),
        publicKey: pair.publicKey()
      };
    })
  )
);
