#!/usr/bin/env node

const axios = require('axios')
const [, pairA, pairB ] = require('../pairs.json')
const { SERVER_URL } = require('./lib/sdk')

const fundAccounts = async (pairs) => await Promise.all(
    pairs.map(
        async (pair) => await axios.get('/friendbot', {
            baseURL: SERVER_URL,
            params: { addr: pair.publicKey }
        })
    )
)

fundAccounts([pairA, pairB])
    .then(() => console.log('ok'))
    .catch((e) => { console.error(e); throw e})
