#!/usr/bin/env node

const axios = require("axios");
const { rootAccountPair } = require("../pairs.json");
const { SERVER_URL } = require("./lib/sdk");

const fundRootAccount = async addr =>
  axios.get("/friendbot", {
    baseURL: SERVER_URL,
    params: { addr }
  });

fundRootAccount(rootAccountPair.publicKey)
  .then(() => console.log("ok"))
  .catch(e => {
    console.error(e);
    throw e;
  });
