#!/usr/bin/env node
const { Stellar, server } = require('./lib/sdk')

const { rootAccountPair, issuingAccountPair, distributionAccountPair } = require('../pairs.json')

const main = async () => {

    const rootAccount = await server.loadAccount(rootAccountPair.publicKey)

    const issuingAccountConfig = {
        destination: issuingAccountPair.publicKey,
        startingBalance: '2.5000000'
    }

    const distributionAccountConfig = {
        destination: distributionAccountPair.publicKey,
        startingBalance: '2.5000000'
    }

    let transaction = new Stellar.TransactionBuilder(rootAccount)
        .addOperation(Stellar.Operation.createAccount(issuingAccountConfig))
        .addOperation(Stellar.Operation.createAccount(distributionAccountConfig))
        .build()

    transaction.sign(Stellar.Keypair.fromSecret(rootAccountPair.secretSeed))

    try {
        await server.submitTransaction(transaction)
    } catch (e) {
        console.log(e.response.data.extras.result_codes);
        throw e
    }

}

main()
    .then(() => { console.log('ok') })
    .catch((e) => { console.error(e); throw e})
