#!/usr/bin/env node
const { Stellar, server } = require('./lib/sdk')

const { issuingAccountPair, distributionAccountPair } = require('../pairs.json')

const main = async () => {

    const distributionAccount = await server.loadAccount(distributionAccountPair.publicKey)

    const sylAsset = new Stellar.Asset('SYL', issuingAccountPair.publicKey)

    const changeTrustOpts = {
        asset: sylAsset,
        limit: '1000',
    }

    let transaction = new Stellar.TransactionBuilder(distributionAccount)
        .addOperation(Stellar.Operation.changeTrust(changeTrustOpts))
        .build()

    transaction.sign(Stellar.Keypair.fromSecret(distributionAccountPair.secretSeed))

    try {
        await server.submitTransaction(transaction)
    } catch (e) {
        console.log(e.response.data.extras.result_codes);
        throw e
    }

}

main()
    .then(() => { console.log('ok') })
    .catch((e) => { console.error(e); throw e})
