#!/usr/bin/env node
const { Stellar, server, TimeoutInfinite } = require("./lib/sdk");

const {
  issuingAccountPair,
  distributionAccountPair
} = require("../pairs.json");

const main = async () => {
  const txOptions = {
    fee: await await server.fetchBaseFee(),
    networkPassphrase: Stellar.Networks.TESTNET
  };

  const distributionAccount = await server.loadAccount(
    distributionAccountPair.publicKey
  );

  const sylAsset = new Stellar.Asset("SYL", issuingAccountPair.publicKey);

  const changeTrustOpts = {
    asset: sylAsset,
    limit: "1000"
  };

  let transaction = new Stellar.TransactionBuilder(
    distributionAccount,
    txOptions
  )
    .addOperation(Stellar.Operation.changeTrust(changeTrustOpts))
    .setTimeout(TimeoutInfinite)
    .build();

  transaction.sign(
    Stellar.Keypair.fromSecret(distributionAccountPair.secretSeed)
  );

  try {
    await server.submitTransaction(transaction);
  } catch (e) {
    console.log(e.response.data.extras.result_codes);
    throw e;
  }
};

main()
  .then(() => {
    console.log("ok");
  })
  .catch(e => {
    console.error(e);
    throw e;
  });
