#!/usr/bin/env node
const { Stellar, server, TimeoutInfinite } = require("./lib/sdk");

const {
  issuingAccountPair,
  distributionAccountPair
} = require("../pairs.json");

const main = async () => {
  const issuingAccount = await server.loadAccount(issuingAccountPair.publicKey);

  const sylAsset = new Stellar.Asset("SYL", issuingAccountPair.publicKey);

  const txOptions = {
    fee: await await server.fetchBaseFee()
  };

  paymentOpts = {
    asset: sylAsset,
    destination: distributionAccountPair.publicKey,
    amount: "1000"
  };

  let transaction = new Stellar.TransactionBuilder(issuingAccount, txOptions)
    .addOperation(Stellar.Operation.payment(paymentOpts))
    .setTimeout(TimeoutInfinite)
    .build();

  transaction.sign(Stellar.Keypair.fromSecret(issuingAccountPair.secretSeed));

  try {
    await server.submitTransaction(transaction);
  } catch (e) {
    console.log(e.response.data.extras.result_codes);
    throw e;
  }
};

main()
  .then(() => {
    console.log("ok");
  })
  .catch(e => {
    console.error(e);
    throw e;
  });
