#!/usr/bin/env node
const { Stellar, server, TimeoutInfinite } = require("./lib/sdk");

const { rootAccountPair, issuingAccountPair } = require("../pairs.json");

const main = async () => {
  const rootAccount = await server.loadAccount(rootAccountPair.publicKey);

  const sylAsset = new Stellar.Asset("SYL", issuingAccountPair.publicKey);

  const txOptions = {
    fee: await await server.fetchBaseFee(),
    networkPassphrase: Stellar.Networks.TESTNET
  };

  const changeTrustOpts = {
    asset: sylAsset
  };

  const manageSellOfferOpts = {
    selling: Stellar.Asset.native(),
    buying: sylAsset,
    amount: "1.00000000",
    price: "1.00000000"
  };

  let transaction = new Stellar.TransactionBuilder(rootAccount, txOptions)
    .addOperation(Stellar.Operation.changeTrust(changeTrustOpts))
    .addOperation(Stellar.Operation.manageSellOffer(manageSellOfferOpts))
    .setTimeout(TimeoutInfinite)
    .build();

  transaction.sign(Stellar.Keypair.fromSecret(rootAccountPair.secretSeed));

  try {
    await server.submitTransaction(transaction);
  } catch (e) {
    console.log(e.response.data.extras.result_codes);
    throw e;
  }
};

main()
  .then(() => {
    console.log("ok");
  })
  .catch(e => {
    console.error(e);
    throw e;
  });
