#!/usr/bin/env node

const { loadTx } = require('./lib/txUtils')
const { server } = require('./lib/sdk')

const dispute = async () => {
    const disputeTx = await loadTx('./disputeT.x')
    await server.submitTransaction(disputeTx)
}

dispute()
    .then(() => { console.log('ok') })
    .catch((e) => { console.log(e.response ? e.response.data.extras.result_codes : e); process.exit(1);})