#!/usr/bin/env node

const { loadTx } = require("./lib/txUtils");
const { Stellar, server } = require("./lib/sdk");
const { mediatorPair } = require("../pairs.json");

const disputeRecover = async () => {
  const disputeRecoverTx = await loadTx("./disputeRecoverT.x");
  disputeRecoverTx.sign(Stellar.Keypair.fromSecret(mediatorPair.secretSeed));
  await server.submitTransaction(disputeRecoverTx);
};

disputeRecover()
  .then(() => {
    console.log("ok");
  })
  .catch(e => {
    console.log(e.response ? e.response.data.extras.result_codes : e);
    process.exit(1);
  });
