#!/usr/bin/env node

const util = require('util')
const pairs = require('../pairs.json')
const { server } = require('./lib/sdk')

const accountExists = (accountResponse => accountResponse instanceof Error ? false : true)

const checkAccounts = async () => {

    const accounts = await Promise.all(
        ['alicePair', 'bobPair', 'escrowPair'].map( async (ref) => {
            try {
                return {
                    ...await server.loadAccount(pairs[ref].publicKey),
                    _accountName: ref
                }
            } catch (e) {
                return e
            }
        })
    )

    return accounts.filter(accountExists).map(account => ({
        name: account._accountName,
        sequence: account.sequence,
        accountId: account.id,
        balances: account.balances.map( balance => 
            `${balance.balance} ${balance.asset_type === 'native' ? 'XLM' : balance.asset_code}`
        )
    }))

}

checkAccounts()
    .then((accounts) => console.log(util.inspect(accounts, false, null)))
    .catch((e) => { console.error(e); throw e})
