#!/usr/bin/env node

const { Stellar, server } = require('./lib/sdk')
const { alicePair, escrowPair } = require('../pairs.json')

const fundEscrow = async () => {

    const aliceAccount = await server.loadAccount(alicePair.publicKey)

    const transaction = new Stellar.TransactionBuilder(aliceAccount)
        .addOperation(Stellar.Operation.payment({
            destination: escrowPair.publicKey,
            asset: Stellar.Asset.native(),
            amount: '100.0000000',
        }))
        .build()
        
    transaction.sign(Stellar.Keypair.fromSecret(alicePair.secretSeed))

    await server.submitTransaction(transaction)

}

fundEscrow()
    .then(() => { console.log('ok') })
    .catch((e) => { console.log(e.response ? e.response.data.extras.result_codes : e); throw e})