#!/usr/bin/env node

const { loadTx } = require('./lib/txUtils')
const { server } = require('./lib/sdk')

const recover = async () => {
    const recoverTx = await loadTx('./recoverT.x')
    await server.submitTransaction(recoverTx)
}

recover()
    .then(() => { console.log('ok') })
    .catch((e) => { console.log(e.response ? e.response.data.extras.result_codes : e); process.exit(1);})